export const tenants = [
  {
    id: 't1',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@gmail.com',
    phone: '+91 98765 43210',
    unit: 'B-402',
    property: 'Prestige Elysian, Bengaluru',
    rent: 45000,
    deposit: 90000,
    leaseStart: '2024-02-01',
    leaseEnd: '2025-01-31',
    status: 'active',
    avatar: 'RS',
    color: '#00D4FF',
    score: 92,
    daysLeft: 74,
  },
  {
    id: 't2',
    name: 'Priya Verma',
    email: 'priya.verma@outlook.com',
    phone: '+91 87654 32109',
    unit: 'A-201',
    property: 'DLF Cyber City Residences, Gurgaon',
    rent: 62000,
    deposit: 124000,
    leaseStart: '2024-04-15',
    leaseEnd: '2025-04-14',
    status: 'active',
    avatar: 'PV',
    color: '#00FF94',
    score: 88,
    daysLeft: 332,
  },
  {
    id: 't3',
    name: 'Aman Singh',
    email: 'aman.singh@yahoo.com',
    phone: '+91 76543 21098',
    unit: 'C-105',
    property: 'Godrej Prana, Pune',
    rent: 28000,
    deposit: 56000,
    leaseStart: '2023-11-01',
    leaseEnd: '2024-10-31',
    status: 'renewal_due',
    avatar: 'AS',
    color: '#FFB547',
    score: 79,
    daysLeft: 12,
  },
  {
    id: 't4',
    name: 'Neha Patel',
    email: 'neha.patel@gmail.com',
    phone: '+91 65432 10987',
    unit: 'D-306',
    property: 'Hiranandani Gardens, Mumbai',
    rent: 78000,
    deposit: 156000,
    leaseStart: '2024-01-10',
    leaseEnd: '2024-12-09',
    status: 'review',
    avatar: 'NP',
    color: '#FF4D6A',
    score: 65,
    daysLeft: 8,
  },
  {
    id: 't5',
    name: 'Kavya Mehta',
    email: 'kavya.mehta@proton.me',
    phone: '+91 54321 09876',
    unit: 'E-501',
    property: 'Logix City Centre, Noida',
    rent: 35000,
    deposit: 70000,
    leaseStart: '2024-06-01',
    leaseEnd: '2025-05-31',
    status: 'onboarding',
    avatar: 'KM',
    color: '#00D4FF',
    score: 95,
    daysLeft: 380,
  },
  {
    id: 't6',
    name: 'Arjun Reddy',
    email: 'arjun.reddy@gmail.com',
    phone: '+91 43210 98765',
    unit: 'B-203',
    property: 'Prestige Elysian, Bengaluru',
    rent: 42000,
    deposit: 84000,
    leaseStart: '2024-03-01',
    leaseEnd: '2025-02-28',
    status: 'active',
    avatar: 'AR',
    color: '#00FF94',
    score: 85,
    daysLeft: 120,
  },
];

export const properties = [
  {
    id: 'p1',
    name: 'Prestige Elysian',
    location: 'Whitefield, Bengaluru',
    units: 48,
    occupied: 44,
    revenue: 1980000,
    type: 'Premium Residential',
    image: 'BE',
  },
  {
    id: 'p2',
    name: 'DLF Cyber City Residences',
    location: 'Sector 24, Gurgaon',
    units: 120,
    occupied: 112,
    revenue: 6944000,
    type: 'Corporate Residential',
    image: 'DG',
  },
  {
    id: 'p3',
    name: 'Godrej Prana',
    location: 'Undri, Pune',
    units: 36,
    occupied: 30,
    revenue: 840000,
    type: 'Mid-Range Residential',
    image: 'GP',
  },
  {
    id: 'p4',
    name: 'Hiranandani Gardens',
    location: 'Powai, Mumbai',
    units: 200,
    occupied: 194,
    revenue: 15132000,
    type: 'Luxury Residential',
    image: 'HM',
  },
];

export const revenueData = [
  { month: 'Jan', revenue: 2840000, target: 2600000 },
  { month: 'Feb', revenue: 3120000, target: 2800000 },
  { month: 'Mar', revenue: 2980000, target: 3000000 },
  { month: 'Apr', revenue: 3450000, target: 3200000 },
  { month: 'May', revenue: 3780000, target: 3400000 },
  { month: 'Jun', revenue: 4100000, target: 3600000 },
  { month: 'Jul', revenue: 3920000, target: 3800000 },
  { month: 'Aug', revenue: 4380000, target: 4000000 },
  { month: 'Sep', revenue: 4650000, target: 4200000 },
  { month: 'Oct', revenue: 4820000, target: 4400000 },
  { month: 'Nov', revenue: 5100000, target: 4600000 },
  { month: 'Dec', revenue: 5340000, target: 4800000 },
];

export const occupancyData = [
  { month: 'Jan', rate: 88 },
  { month: 'Feb', rate: 90 },
  { month: 'Mar', rate: 87 },
  { month: 'Apr', rate: 92 },
  { month: 'May', rate: 94 },
  { month: 'Jun', rate: 96 },
  { month: 'Jul', rate: 93 },
  { month: 'Aug', rate: 95 },
  { month: 'Sep', rate: 97 },
  { month: 'Oct', rate: 95 },
  { month: 'Nov', rate: 96 },
  { month: 'Dec', rate: 98 },
];

export const aiInsights = [
  {
    id: 'ai1',
    type: 'urgent',
    title: '3 lease renewals due within 14 days',
    description: 'Aman Singh (C-105), Neha Patel (D-306), and Rohit Kumar (A-108) have leases expiring soon. Initiate renewal workflow.',
    action: 'Start Renewal',
    icon: 'calendar',
  },
  {
    id: 'ai2',
    type: 'warning',
    title: 'AI detected incomplete tenant verification',
    description: 'Kavya Mehta\'s Aadhaar verification is pending. Identity match confidence at 67% — manual review recommended.',
    action: 'Review Documents',
    icon: 'shield',
  },
  {
    id: 'ai3',
    type: 'alert',
    title: 'Tenant payment pattern indicates elevated risk',
    description: 'Neha Patel (D-306) has 2 delayed payments in past 3 months. AI risk score dropped from 82 to 65.',
    action: 'View Profile',
    icon: 'trending',
  },
  {
    id: 'ai4',
    type: 'info',
    title: 'Unit inquiry volume increased by 47%',
    description: 'DLF Cyber City Residences saw a 47% spike in inquiries this week. 12 new leads added to the pipeline.',
    action: 'View Leads',
    icon: 'chart',
  },
  {
    id: 'ai5',
    type: 'success',
    title: 'Lease draft ready for Kavya Mehta',
    description: 'HiveAI has auto-generated a lease agreement for E-501 based on standard template. Requires manager signature.',
    action: 'Review Lease',
    icon: 'document',
  },
];

export const activityFeed = [
  { id: 'a1', type: 'verify', text: 'Documents verified for Rahul Sharma', time: '2 min ago', avatar: 'RS', color: '#00FF94' },
  { id: 'a2', type: 'lease', text: 'Lease generated for Kavya Mehta — E-501', time: '18 min ago', avatar: 'KM', color: '#00D4FF' },
  { id: 'a3', type: 'message', text: 'New message from Priya Verma re: maintenance', time: '1 hr ago', avatar: 'PV', color: '#FFB547' },
  { id: 'a4', type: 'visit', text: 'Property visit scheduled — Logix City Centre', time: '2 hr ago', avatar: 'AI', color: '#00D4FF' },
  { id: 'a5', type: 'screening', text: 'AI screening completed for new applicant Vikram Das', time: '3 hr ago', avatar: 'VD', color: '#FF4D6A' },
  { id: 'a6', type: 'payment', text: 'Rent payment received from Arjun Reddy — ₹42,000', time: '5 hr ago', avatar: 'AR', color: '#00FF94' },
  { id: 'a7', type: 'verify', text: 'Identity verification started for Deepa Nair', time: '6 hr ago', avatar: 'DN', color: '#00D4FF' },
  { id: 'a8', type: 'alert', text: 'Maintenance request raised by Aman Singh — C-105', time: '8 hr ago', avatar: 'AS', color: '#FFB547' },
];

export const messages = [
  {
    id: 'm1',
    tenant: 'Priya Verma',
    avatar: 'PV',
    color: '#00FF94',
    lastMessage: 'The AC unit in the bedroom has been making a loud noise since yesterday...',
    time: '10:42 AM',
    unread: 2,
    thread: [
      { sender: 'tenant', text: 'Hi, the AC unit in the bedroom has been making a loud noise since yesterday. Could you please look into it?', time: '10:30 AM' },
      { sender: 'ai', text: 'I\'ve logged a maintenance request for AC repair at A-201. Our team will contact you within 24 hours. Reference: MR-2847', time: '10:32 AM' },
      { sender: 'tenant', text: 'Thank you! Also, when is my next rent due?', time: '10:42 AM' },
    ],
  },
  {
    id: 'm2',
    tenant: 'Rahul Sharma',
    avatar: 'RS',
    color: '#00D4FF',
    lastMessage: 'Thank you for the lease renewal documents. I\'ve reviewed them.',
    time: 'Yesterday',
    unread: 0,
    thread: [
      { sender: 'admin', text: 'Hi Rahul, please find your lease renewal documents attached. Kindly review and sign digitally by end of week.', time: 'Yesterday 3:00 PM' },
      { sender: 'tenant', text: 'Thank you for the lease renewal documents. I\'ve reviewed them and everything looks good. I\'ll sign today.', time: 'Yesterday 5:30 PM' },
    ],
  },
  {
    id: 'm3',
    tenant: 'Kavya Mehta',
    avatar: 'KM',
    color: '#00D4FF',
    lastMessage: 'Can I schedule a property visit this weekend?',
    time: 'Mon',
    unread: 1,
    thread: [
      { sender: 'tenant', text: 'Hello! I\'m interested in Unit E-501 at Logix City Centre. Can I schedule a property visit this weekend?', time: 'Mon 11:15 AM' },
    ],
  },
  {
    id: 'm4',
    tenant: 'Aman Singh',
    avatar: 'AS',
    color: '#FFB547',
    lastMessage: 'My lease is expiring in 12 days. What are the renewal terms?',
    time: 'Sun',
    unread: 1,
    thread: [
      { sender: 'tenant', text: 'My lease is expiring in 12 days. What are the renewal terms? Will there be a rent increase?', time: 'Sun 9:00 AM' },
    ],
  },
];

export const tenantJourney = {
  name: 'Rahul Sharma',
  unit: 'B-402',
  property: 'Prestige Elysian, Bengaluru',
  progress: 75,
  steps: [
    { id: 1, label: 'Application Submitted', status: 'done', date: 'Jan 15, 2024', description: 'Online application completed and submitted' },
    { id: 2, label: 'Documents Uploaded', status: 'done', date: 'Jan 17, 2024', description: 'Aadhaar, PAN, and bank statement verified' },
    { id: 3, label: 'AI Verification Complete', status: 'done', date: 'Jan 18, 2024', description: 'Identity and credit check passed with 92% score' },
    { id: 4, label: 'Lease Review In Progress', status: 'active', date: 'Jan 20, 2024', description: 'Agreement being reviewed by property manager' },
    { id: 5, label: 'Digital Signature Pending', status: 'pending', date: '', description: 'E-sign the agreement once approved' },
    { id: 6, label: 'Move-In Ready', status: 'pending', date: '', description: 'Key handover and welcome kit' },
  ],
};

export const tenantNotifications = [
  { id: 'n1', type: 'action', title: 'Upload Aadhaar card to complete verification', time: '2 hours ago', read: false },
  { id: 'n2', type: 'success', title: 'Identity verification 80% complete', time: '5 hours ago', read: false },
  { id: 'n3', type: 'info', title: 'Property manager reviewed your application', time: '1 day ago', read: true },
  { id: 'n4', type: 'action', title: 'Lease ready for signature', time: '1 day ago', read: true },
  { id: 'n5', type: 'success', title: 'Rent payment confirmed — ₹45,000', time: '3 days ago', read: true },
];

export const formatCurrency = (amount: number): string => {
  if (amount >= 10000000) return `₹${(amount / 10000000).toFixed(1)}Cr`;
  if (amount >= 100000) return `₹${(amount / 100000).toFixed(1)}L`;
  if (amount >= 1000) return `₹${(amount / 1000).toFixed(0)}K`;
  return `₹${amount}`;
};
